---
# handlers file for pgsql
- name: Stop pgsql
  ansible.builtin.systemd:
    state: stopped
    name: postgresql
    listen: stop_pgsql

- name: Start pgsql  
  ansible.builtin.systemd:
    state: started
    name: postgresql
    listen: start_pgsql
